### ISSUE TITLE
"Cannot download app" with Chrome 34

### ISSUE THREAD

**Issue by bombadier** [Lekensteyn/apk-downloader#11]
Testing the new version on Chrome canary 34.0.1833.4
Have a vaild email address and android device ID entered but keep getting the "Cannot download app" error 

Trying to download 
https://play.google.com/store/apps/details?id=org.hermit.netscramble

Ok have used the Device ID for my Nexus 7 and is working with the above app,wonder why my phone ID is not working?

**Comment by Lekensteyn** [comment]
I cannot reproduce the error with Chromium 34. Is your phone compatible with the app? Can you see the phone on the devices list on the Play Store website? If you navigate to the app page, do you see the ability to install to your phone from that page?

What Android version are you running?

**Comment by dSeeder** [comment]
I was able to download that app. Tried with Nexus 7 and a bunch of other devices.

**Comment by bombadier** [comment]
Using Scrambled Net as my test app,yes the nexus 4 is compatible,running 4.4.2

**Comment by bombadier** [comment]
Ok issue can be closed,looks like my GSF ID for the nexus 4 has changed,everything working now I am using the new ID
Thanks
