### ISSUE TITLE
429 Unknown Error

### ISSUE THREAD

**Issue by vahidkaargar** [Lekensteyn/apk-downloader#2]
Hi,

when i want to download an app with "APK Downloader" i got this error:

ERROR: Cannot download this app!
429 unknown

can you explain to me why?

thanks.

**Comment by Rob--W** [comment]
What's the URL of the app you're trying to download?

**Comment by vahidkaargar** [comment]
https://play.google.com/store/apps/details?id=com.sothree.umano

**Comment by vahidkaargar** [comment]
for everything that i want to download i got this error

**Comment by vahidkaargar** [comment]
i mean every app in google market

**Comment by Rob--W** [comment]
You're experiencing this issue: https://groups.google.com/forum/#!topic/android-market-api/_xYmXq5gfmM

I can't test the extension right now, but I'll ping Peter (Lekensteyn).

**Comment by Lekensteyn** [comment]
Works for me, have you tried logging out at the options page and logging in again?

**Comment by vahidkaargar** [comment]
the problem resolved, but i didnt find the problem!

**Comment by Lekensteyn** [comment]
Well, that sounds contradictory, but it looks like it can be closed.
