### ISSUE TITLE
ERROR: authentication failed

### ISSUE THREAD

**Issue by dSeeder** [Lekensteyn/apk-downloader#21]
Incorrect username or password.

While everything is correct to my test. I think the new client login update blown this.

**Comment by Walkman100** [comment]
#16

**Comment by Lekensteyn** [comment]
Looks like #20. I have received multiple reports, also by mail, but haven't found time to reply to those or further investigate this. (closing as duplicate)

**Comment by dSeeder** [comment]
Thank you WalkMan for addressing the issue.After turning it off, i can sign in. But Peter, is there any way to make this app from less secure to more secure?

**Comment by Lekensteyn** [comment]
@dSeeder None of these interfaces were really documented, I would have to dig to find alternatives. The best you can do for now is enable 2FA.
