### ISSUE TITLE
What's difference between your apk downloader and google play app?

### ISSUE THREAD

**Issue by vahidkaargar** [Lekensteyn/apk-downloader#4]
Hello,

I tried to download app with your apk downloader but i got 429 error but with my device i could download successfully that app, why?

P.S.: IP, Google Account and DeviceID are similar.

**Comment by Lekensteyn** [comment]
In reply to the question in the title: the Google Play application:
- communicates using the Google Services Framework;
- works only on Android devices;
- is made by Google, not me;
- uses different APIs
- uses a different authentication method;
- installs APKs immediately without giving you a chance to look at its contents;
- Can execute code on installation;
- Is closed source.

Whereas this "APK Downloader" is open-source under a GPLv3 license, you can study its functionality as you want.

I haven't encountered the 429 error. Can you give steps for reproduction in a well-defined environment, such as the Android emulator?
