### ISSUE TITLE
This extension not works anymore

### ISSUE THREAD

**Issue by vahidkaargar** [Lekensteyn/apk-downloader#6]
Hi,
Last day with google play update, i cant use this extension anymore, can you fix this?

**Comment by Lekensteyn** [comment]
This has been reported by another user by mail already, if time permits I will have a look at it.

**Comment by vahidkaargar** [comment]
thank you

**Comment by Rob--W** [comment]
This has already been fixed two months ago with version 1.5.0 - https://github.com/Lekensteyn/apk-downloader/compare/99ae858a3...v1.5.0.

If it hasn't, please open a new issue.
