### ISSUE TITLE
seems to have stopped working?

### ISSUE THREAD

**Issue by 0xc1c4da** [Lekensteyn/apk-downloader#8]
As of today I get "Cannot download app, maybe it is a paid one or something?" on 1.5.0, no errors in console. Nothing in network log, I'm signed in and everything was working a week ago?

**Comment by Lekensteyn** [comment]
Have you tried logging out and logging in again at Settings? What app are you trying to download (and what language is the page?)

**Comment by 0xc1c4da** [comment]
eh sorry, logging out/logging back in within the extension made it work again.
